FROM registry.jharmison.com/l4t/image:latest

# Enable journal output on TTY1
COPY overlays/debug/ /

# Install some useful developer tools and environment niceties
RUN --mount=target=/var/cache,type=tmpfs --mount=target=/var/cache/dnf,type=cache,id=dnf-cache \
    dnf -y install \
      make \
      gcc \
      g++ \
      git \
      neovim \
      buildah \
      skopeo \
      python3.12 \
      python3.12-devel \
      python3.12-pip-wheel \
      fastfetch
