RUNTIME ?= podman
REGISTRY ?= registry.jharmison.com
REPOSITORY ?= l4t/image
BASE ?= registry.redhat.io/rhel9/rhel-bootc:9.4
MIRRORED_BASE ?= $(REGISTRY)/$(REPOSITORY):base
TAG ?= latest
IMAGE = $(REGISTRY)/$(REPOSITORY):$(TAG)
