RUNTIME ?= podman
REGISTRY ?= docker.io
REPOSITORY ?= tinkster42/jetson-orin
BASE ?= registry.redhat.io/rhel9/rhel-bootc:9.4
MIRRORED_BASE ?= $(REGISTRY)/$(REPOSITORY):base
TAG ?= latest
IMAGE = $(REGISTRY)/$(REPOSITORY):$(TAG)
